### PR TITLE
Add svelte-compare-image-slider package

### PR DESCRIPTION
**Pull request by johnwalley**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit c55d97c5fcd2e47bc81a49f816d93924145415c8

https://deploy-preview-246--svelte-community.netlify.app

**Comment by frederikhors** [comment]
There is some problem here.

**Comment by frederikhors** [comment]
@sw-yx

**Review by swyxio — CHANGES_REQUESTED** [review]
pls dont reformat the whole file

**Comment by johnwalley** [comment]
Very sorry about that! Apologies for wasting your time over a silly mistake. I've fixed up the commit

**Comment by frederikhors** [comment]
Amazing project. Thanks.

**Review by swyxio — APPROVED** [review]

**Pull request merged**
