### PR TITLE
add Who's Using Svelte list and logos

### PR DESCRIPTION
**Pull request by Conduitry**
I'd like to offload the responsibility for vetting and merging these on the 'community' team if y'all don't mind.

We can think later about whether we want to show fewer logos on the homepage itself and put the rest of them only on a community page - but in the meantime this PR goes along with a forthcoming https://github.com/sveltejs/svelte PR that copies these files in during the site's build process, and the homepage will continue to look exactly as it does now.

Thanks!

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit ca33994a2844b51f27d7b186513f6be6e456b296

https://deploy-preview-57--svelte-community.netlify.com

**Comment by Conduitry** [comment]
I've also just compressed all SVGs (with `svgo`) and all PNGs (with `optipng`), and I'd like it if these could continue to be run on future additions to this list.

**Comment by Conduitry** [comment]
I'm not sure what this build failure is, but if it has to do with where I put the new directory, let me know and I'll move it.

**Comment by Conduitry** [comment]
Moving the `whos-using-svelte` directory out of `data`, which seems to have fixed the build error. Also added two pending logo additions from https://github.com/sveltejs/svelte/pull/4099 and https://github.com/sveltejs/svelte/pull/4210

**Comment by swyxio** [comment]
happy to handle this - sorry for delayed feedback. need to do a lot more work on this site to keep it up to snuff!

**Pull request merged**
