### PR TITLE
add in1 logo

### PR DESCRIPTION
**Pull request by lkalinowski**
in1 is e-commerce platform (in our beginning). We will develop our product in order to deliver all necessary stuff to run small and medium size company online - all in 1 ;)
We use Svelte for our admin panel. Started with one view which user loved. So now, we redesign whole admin app with Svelte.

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 17001b4ab371ab5989ec012426d0f77b37768783

https://deploy-preview-62--svelte-community.netlify.com

**Comment by kevmodrome** [comment]
It doesn't look like you're using Svelte anywhere?

**Comment by lkalinowski** [comment]
As I mentioned in PR description we use Svelte in admin panel only. So let me prepare demo account for you, @kevmodrome . I'll provide you credentials soon

**Comment by lkalinowski** [comment]
> It doesn't look like you're using Svelte anywhere?

@kevmodrome please login to our panel and check file manager:
https://demo.in1.pl/panel/file_manager
https://demo.in1.pl/panel/menus/4/edit
https://demo.in1.pl/panel/paragraphs/new

That are pieces we started with. Now we work on page editor in svelte ( https://demo.in1.pl/panel/pages/63/edit ).
Login is: demo@in1.pl

Can I send you password via email? Please leave your email or write to me lukasz@in1.pl

**Review by swyxio — APPROVED** [review]

**Pull request merged**
