### PR TITLE
Add SwissDevJobs logo

### PR DESCRIPTION
**Pull request by Vrq**
We are using Svelte for a new mini-site and it feels awesome! ⭐

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 41ebc35370310a1eaa4745851ba199e275840de4

https://deploy-preview-75--svelte-community.netlify.com

**Comment by kevmodrome** [comment]
Is this something you can show us, maybe? :)

**Comment by Vrq** [comment]
@kevmodrome sure :)

You can find the preview on: https://software-salary-calculator.netlify.com

**Comment by Vrq** [comment]
@kevmodrome did you have some time to have a look? :)

**Review by swyxio — APPROVED** [review]

**Comment by swyxio** [comment]
edited to reflect for you!

**Pull request merged**
