### PR TITLE
add ability to toggle tags to filter resources

### PR DESCRIPTION
**Pull request by ryanatkn**
- Adds a `<Tag/>` component that can be clicked to toggle its selection state.
- Adds a bank of tags underneath the search bar. As this grows it's going to be a mess and it's already unwieldy, so the UX needs to be rethought.
- The resources are filtered based on the selected tags - if any tags overlap, the resource is included. This UX seems difficult to get right - maybe a simple AND/OR toggle in the UI would be nice. (it currently defaults to OR, meaning all resources are included that have `selectedTag1 OR selectedTag2` etc)
- The styling is minimal and mostly badly hardcoded, just enough to get things presentable.

I'm still plaiying with patterns for writing components and don't yet know which I prefer and why, so consider this a first pass that just gets the basic functionality. If anyone wants to bikeshed the code, any input is welcome. 

The main code thing I wanted feedback on is that I don't like how `<Resource/>` has the `selectedTags` prop so it can render its tags. The `toggleTag` prop also seems like it may be outside of its concern. Maybe stores would be better here, coupling the tag name, selected state, and toggle function? Or how about a slot, forcing the `<Resource/>` parent to render the tags?

svelte_community_tags

### CODE REVIEW

**Comment by kevmodrome** [comment]
This is tough - I didn't realize  there were this many tags. I experimented with making something similar earlier today but never made anything I was satisfied with. 

In general I like the idea of being able to filter by tag but we probably need to rework this. Could we have a category + sub-category type of system instead of tags, maybe?

**Comment by kevmodrome** [comment]
I think we can make the information (the list itself) a bit more dense as well without being overwhelming, I will do some mockups tomorrow.

**Comment by ryanatkn** [comment]
I like the idea of having hierarchical categories. That's how the original data is set up, so it'd be easy to convert it. I'll throw together a quick script soon to get that data so we can play with it.

Orthogonal tags not bound to to a single category are also useful - like "official" and "videos". Does it make more sense to have one system or two? This could be implemented with resources belonging to many categories.

Also I opened up an issue to discuss tags after a recent submission prompted me to - https://github.com/sveltejs/community/issues/23

**Comment by joakim** [comment]
I also see the need to be able to filter on tags, with the list being so long. Anything that quickly and easily lets you narrow the list down to the part that you're interested in would be a win.

**Comment by ryanatkn** [comment]
@joakim I agree, the cloud of tags already doesn't scale. I like the searchable multi select with inline-rendered selections like [`svelte-select`](https://github.com/rob-balfre/svelte-select) has - https://svelte.dev/repl/f3bc0fd6b6f74ea499e5ecb26911bf28?version=3.12.1 (see the Multi example) There are some other ways to do this too, and the form that tags take may guide that decision.

**Comment by swyxio** [comment]
ok lets work on the tags in a separate PR, this is a solid improvement and [already being requested](https://www.reddit.com/r/sveltejs/comments/dgjuus/new_svelte_community_site_now_with_searchable/f3e00y2/)

**Review by swyxio — APPROVED** [review]

**Pull request merged**
