### PR TITLE
Add myorganisation logo

### PR DESCRIPTION
**Pull request by alextomas80**
Added my logo

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 5562ee3c4b2758799e761d699b0b78d96e868123

https://deploy-preview-380--svelte-community.netlify.app

**Review by dreitzner — CHANGES_REQUESTED** [review]
@alextomas80 please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

**Comment by alextomas80** [comment]
> @alextomas80 please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

done!

**Comment by dreitzner** [comment]
> > @alextomas80 please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js
> 
> done!

Please resolve the conflicts by [syncing with upstream](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by dreitzner** [comment]
@alextomas80 I guess this PR can be closed, as you created a new one, right?

**Pull request closed without merging**
