### PR TITLE
Add Vime library to Code

### PR DESCRIPTION
**Pull request by mihar-22**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 8146804067fdb9cad42a01587c34a61e740f8929

https://deploy-preview-158--svelte-community.netlify.com

**Comment by ryanatkn** [comment]
This is stellar, great docs.

Currently it adds these tags:

```yml
- video
- audio
- player
- youtube
- vimeo
- dailymotion
- html5
```

All of these are new but some probably belong. We've been trying to keep a small set so they remain useful. Video and audio seem appropriate to me, the others less so. Any thoughts?

Under current conventions the following tags should probably be added: (if you think they could be improved opening an issue would be good)

```yml
- components and libraries
- inputs and widgets
```

**Comment by mihar-22** [comment]
Agreed @ryanatkn and I've pushed the new changes.

**Comment by ryanatkn** [comment]
Looks good thanks!

Since it has multiple npm packages it doesn't fit into our currently limited pattern of putting the name in backticks to reference the npm package. (the PR properly leaves out the backticks) We may want to support a new property to handle cases like this one, so you can name it "Vime" but also reference npm packages `@vime-js/lite`, `@vime-js/standard`, etc, within one entry, and get npm download stats and linkage to at least one of them. There are many ways to fit this into what we have already, so if anyone has a good proposal please open an issue.

**Pull request merged**
