### PR TITLE
svelte-atoms ui kit added

### PR DESCRIPTION
**Pull request by az67128**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 3adbc5eb063e410261bc9d70f5449f21502ae443

https://deploy-preview-150--svelte-community.netlify.com

**Comment by ryanatkn** [comment]
Looks great, also it's the first GitLab submission so I added the issue linked above so we'll be sure to keep its stats in sync.

edit: I can't see why the build is failing, not going to approve yet. I verified that it works locally. (and the script too, though I think that shouldn't matter?)

**Comment by az67128** [comment]
So, I pushed it once again and build passed

**Comment by ryanatkn** [comment]
Thanks, that was a forehead smacking moment for me.

**Pull request merged**
