### PR TITLE
Alex Tomás added

### PR DESCRIPTION
**Pull request by alextomas80**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 5dcf1868449e2a00e11dfd5de532fda25449a175

https://deploy-preview-383--svelte-community.netlify.app

**Review by dreitzner — CHANGES_REQUESTED** [review]
@alextomas80 you forgot to add your image at `organisations/alextomas.png`

**Comment by alextomas80** [comment]
> @alextomas80 you forgot to add your image at `organisations/alextomas.png`

I can not add images on master. How i can do it ?

**Comment by dreitzner** [comment]
> > @alextomas80 you forgot to add your image at `organisations/alextomas.png`
> 
> I can not add images on master. How i can do it ?

You need to commit to your [own branch](https://github.com/alextomas80/community/tree/patch-1)

**Comment by alextomas80** [comment]
> > > @alextomas80 you forgot to add your image at `organisations/alextomas.png`
> > 
> > 
> > I can not add images on master. How i can do it ?
> 
> You need to commit to your [own branch](https://github.com/alextomas80/community/tree/patch-1)

Done! https://github.com/sveltejs/community/pull/385

**Comment by benmccann** [comment]
Can you put the two changes in a single PR?

**Comment by alextomas80** [comment]
I close it. I will do it in another pull request

**Pull request closed without merging**
