### PR TITLE
add Resources

### PR DESCRIPTION
**Pull request by swyxio**
basic first cut.. needs some css work and i havent checked the responsiveness

potato

### CODE REVIEW

**Comment by swyxio** [comment]
to close @ryanatkn's https://github.com/ryanatkn/awesome-svelte-resources/issues/18

**Comment by swyxio** [comment]
lol deploy preview already ready! https://deploy-preview-16--svelte-community.netlify.com/resources

**Comment by ryanatkn** [comment]
Yay this is great. Has there been more discussion about whether resources belong in this community repo long-term? I liked [how pngwn framed it](https://github.com/ryanatkn/awesome-svelte-resources/issues/18#issuecomment-538701998) in terms of thinking about what the ideal website(s) look like when they're mature.

**Comment by swyxio** [comment]
no idea man. just winging it. nobody seems to have a strong opinion and with only 200+ resources we arent hitting real scale problems yet

**Comment by ryanatkn** [comment]
Sounds good, it could always be split apart. I'm excited to play around with some improvements.

**Comment by pngwn** [comment]
Yeah, I'm more on the side of 'this should be somewhere else' currently, probably with some other resources to aid discoverability when people are reading docs or guides. That said this isn't going to happen instantly, so I'm happy for this to at least have a home for the time being. If we decide it should go somewhere else in the future then it isn't a big deal to relocate it.

**Pull request merged**
