### PR TITLE
Adds tweak to showcase

### PR DESCRIPTION
**Pull request by danielcaldas**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit eb1752147faf4a4aad0e6c3232421b18e2dfca4e

https://deploy-preview-212--svelte-community.netlify.app

**Comment by benmccann** [comment]
This doesn't seem specifically related to svelte. I'm not sure whether the site has general development tools or not

**Comment by Conduitry** [comment]
Indeed, this doesn't seem particularly relevant.

Edit: Unless it's written in Svelte? I didn't download the extension to find out. It doesn't appear to be open source. I guess I'll reopen this and let someone else decide. I do see that there appear to be one other entry in the showcase without a link to a repository. I feel like that sort of thing should be discouraged or perhaps disallowed though, because otherwise this section of the site is just going to turn into free advertising.

**Comment by danielcaldas** [comment]
@Conduitry 
The extension is written in Svelte. But it is not an Open Source project.

> because otherwise, this section of the site is just going to turn into free advertising.

Yes, that's a good point. I don't want to spam the community showcase for that I'll take down my PR.

Cheers!

**Pull request closed without merging**
