### PR TITLE
add/whos-using-svelteKit

### PR DESCRIPTION
**Pull request by Fredrikwide**
if we want i added a whos-using-sveltekit option now that svelte-kit is in open beta for future usage.

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 8a1927921982a69dbda6113a4b483e25bbcb4b39

https://deploy-preview-430--svelte-community.netlify.app

**Review by dreitzner — COMMENTED** [review]
Would it be possible to include at least the boilerplate for the .js and .svelte file?

Other than that, great idea 👍

**Comment by Fredrikwide** [comment]
Yupp i thought i added them already. 🤷‍♂️  Do you want me to update this pr or create a new one with the added boilerplates?

**Comment by dreitzner** [comment]
> Yupp i thought i added them already. 🤷‍♂️  Do you want me to update this pr or create a new one with the added boilerplates?

Just add it to this one

**Comment by Fredrikwide** [comment]
Done, Or I don't know any current companies using svelteKit in production (I hope no one) so I just added the empty array : )

**Review by dreitzner — APPROVED** [review]

**Pull request merged**
