### PR TITLE
Set up initial Showcase work

### PR DESCRIPTION
**Pull request by swyxio**
Showcase is important for people to get social proof and visual inspiration. it is a lot of work to set up a good showcase, so it kept getting put off, and i didnt like that. so here's some initial work on it.

image

needs a lot of design love. but will start giving the vision.

we may need to add the RHS tag filter in future, but for now lets just punt on it

i also punted on image processing but ofc we can do a much better job.

### CODE REVIEW

**Comment by swyxio** [comment]
one styling note that confused me is that @sveltejs/sitekit has a css reset that sets that `<a>` tag styling https://github.com/sveltejs/site-kit/blob/master/base.css#L300-L310 this is leaky and very annoying and we may wish to fork sitekit

**Review by kevmodrome — APPROVED** [review]
👍

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 729a845967b9b2e725d1e994e32ae3ce67ff0748

https://deploy-preview-39--svelte-community.netlify.com

**Comment by ourway** [comment]
@sw-yx Awesome, I am trying to **open source the whole code**. It may take a week or so to persuade the client.  If that not happens, I will open source components.

Thanks all for your positive energy.

**Comment by swyxio** [comment]
gotta work together to jumpstart this new community :)

**Pull request merged**
