### PR TITLE
Add Transloadit logo

### PR DESCRIPTION
**Pull request by nqst**
Hey! We at [Transloadit](https://transloadit.com) would like to add our logo to your list 🤖

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 7d4197639f78c208e2a530a43dee1e9061f919f5

https://deploy-preview-313--svelte-community.netlify.app

**Comment by swyxio** [comment]
welcome! is your svelte app public? i cant see it on your landing page

**Comment by nqst** [comment]
Thank you!

We’re making official Svelte bindings for [Uppy](https://uppy.io), our open-source file uploader (https://github.com/transloadit/uppy/pull/2408).

If you have any feedback on that, just let us know, it's very welcome :)

**Comment by swyxio** [comment]
ooh nice :) tag @sveltesociety on twitter when released!

**Pull request merged**
