### PR TITLE
Added Philips to the list of companies using Svelte

### PR DESCRIPTION
**Pull request by mattpilott**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 14515d30fb97f4d73d51944b73c4a0a265b50a94

https://deploy-preview-220--svelte-community.netlify.app

**Comment by swyxio** [comment]
welcome Philips!

**Comment by arxpoetica** [comment]
Hey @matt3224 this is awesome. I'm noticing the SVG file is huge, and has some sort of weird fuzzy / holes-in-it problem. Notice all the empty white spots and the faint stripe next to the "I".

image

Any chance we can get that SVG cleaned up?

**Comment by mattpilott** [comment]
Of course, ill get a better over today

**Comment by swyxio** [comment]
addressed in https://github.com/sveltejs/community/pull/222

**Pull request merged**
