### PR TITLE
Display metadata

### PR DESCRIPTION
**Pull request by swyxio**
we have stars and last updated, lets show it

i also updated the ssg dep

image

### CODE REVIEW

**Review by ryanatkn — APPROVED** [review]
Looks good to me. That information is great to see.

The "Last " part of "Last updated" seems like it could be removed.

I looked to see how things are with the stars/date swapped but it's a wash to me. The variable width of the star count works well right-aligned, but it's wonky when the date is right-aligned.
pic0
pic1

**Comment by kevmodrome** [comment]
This looks lit!

**Comment by kevmodrome** [comment]
can this be merged?

**Comment by ryanatkn** [comment]
@sw-yx any reservations to merging this? Once it's in we can extend to include the npm monthly download stats. ⭳

**Comment by swyxio** [comment]
sorry just saw this 😂  been MIA for a bit

**Pull request merged**
