### PR TITLE
Add Alaska Airlines logo

### PR DESCRIPTION
**Pull request by geoffrich**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 5612d298ed99033a3425076f2e3734e3e4d0848d

https://deploy-preview-265--svelte-community.netlify.app

**Comment by swyxio** [comment]
whoa. where do you use it in ALK?

**Comment by geoffrich** [comment]
@sw-yx we're using it in a new microsite we built to help guests when their flight is disrupted. The guest is often at the airport when they get the notification (slow connection speeds) so we chose Svelte to keep our JS payload low.

**Comment by swyxio** [comment]
thats awesome!!! i love flying Alaska. keep up the great work!!

**Pull request merged**
