### PR TITLE
inlum link added

### PR DESCRIPTION
**Pull request by intlum-web**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 8ff67ea0476bc1a0623a7ad83f3bdf30aa7c77b8

https://deploy-preview-332--svelte-community.netlify.app

**Comment by peopledrivemecrazy** [comment]
@intlum-web We are glad you are using svelte, please rearrange the logo according to your alphabet. The instructions are on the top of the file in the comments.

**Comment by swyxio** [comment]
i rather we change the submissions to make it easier to submit and harder to get wrong

**Comment by dreitzner** [comment]
@sw-yx 
maybe i could implement sorting inside of #377 ?
just would need to pay attention to special chars like `&`, `Æ`, `&`,.....

**Comment by swyxio** [comment]
would be fine with that yea

**Review by dreitzner — CHANGES_REQUESTED** [review]
@intlum-web please pull in the latest changes and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

**Comment by benmccann** [comment]
I don't see Svelte being used on the site. This looks like a Wordpress site. Also, it says technologies used React, Vue.js, jQuery, but Svelte is not mentioned.

This has also gone months without being rebased as required, so I'm going to close this

**Pull request closed without merging**
