### PR TITLE
add phonerefer logo locally and fix alt text

### PR DESCRIPTION
**Pull request by ryanatkn**
This fixes two inconsistencies with the Phone Refer logo - the logo wasn't included locally and its alt text lacked "logo" like the others.

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit a5ffd2ffcb5a59ff8244b3f9ac2987f00ec0f3bd

https://deploy-preview-136--svelte-community.netlify.com

**Review by kevmodrome — APPROVED** [review]

**Comment by swyxio** [comment]
thanks guys. trying to get back in the swing of things. been busy changing companies and countries.

**Comment by ryanatkn** [comment]
Countries! Where you at?

**Comment by swyxio** [comment]
singapore lol. imagine heading to *asia* to hide out a crisis that started in china.

**Pull request merged**
