### PR TITLE
Add gojek logo in WhosUsingSvelte.

### PR DESCRIPTION
**Pull request by digi0ps**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit dbcb91c6ba422d95a650f6a48b6b7a6de2116139

https://deploy-preview-275--svelte-community.netlify.app

**Comment by digi0ps** [comment]
Hey @sw-yx, I don't see the logo in the [homepage](https://svelte.dev) yet. 😕 
Is there anything wrong?

**Comment by swyxio** [comment]
typically requires them to redeploy in order for it to update, we are not connected via CI/CD here.

btw what are you using it for at gojek? would love to share your story on the Svelte Society Twitter, get gojek engineering some attention

**Comment by digi0ps** [comment]
@sw-yx I'm so sorry, I totally missed this and just found this right now while going through my older mails.

We have used Svelte to create an internal tool to debug and analyse the routes we show to customers. And yesss, would love to share the story!

**Comment by peopledrivemecrazy** [comment]
Gojek uses svelte?  😮

**Pull request merged**
