### PR TITLE
Add General Mills Logo & Standardize Trailing Comma to ES5

### PR DESCRIPTION
**Pull request by CreationEdge**
Added GMI logo and entry in WhoIsUsing
Standardized object entries with trailing commas and consistent spacing, since some entries were not indented equally and trailing comma was not consistent.

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit ad557f0b8679320cbf3d13347c191c44bca6d903

https://deploy-preview-407--svelte-community.netlify.app

**Review by dreitzner — APPROVED** [review]
LGTM :)

Thank you for the indent fix

**Comment by swyxio** [comment]
need to resolve conflicts :(

**Review by dreitzner — CHANGES_REQUESTED** [review]
please resolve conflicts

**Comment by benmccann** [comment]
It would be preferable to change indentation and commas in a separate PR. It's impossible to look at this to tell what's changed

**Pull request closed without merging**
