### PR TITLE
Add crocodaily logo

### PR DESCRIPTION
**Pull request by sharu725**
add logo

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 53d801de92d3123973a198d3b65890dd14991d87

https://deploy-preview-355--svelte-community.netlify.app

**Comment by peopledrivemecrazy** [comment]
@sharu725 can you bring the changes to one of the PRs and close #354 

@sw-yx or can you merge them both?

**Comment by sharu725** [comment]
@peopledrivemecrazy sorry about two PRs. I can make a single PR. 
Let me know @sw-yx

**Comment by swyxio** [comment]
merged both

**Pull request merged**
