### PR TITLE
update ssg dependencies

### PR DESCRIPTION
**Pull request by swyxio**
just keeping things from falling too far behind, as i evolve the ssg plugin api's

its mergeable as is, just following protocol by making a PR. I'm also going to try to put @pngwn's new mdsvex to work in a followup version of ssg

### CODE REVIEW

**Review by kevmodrome — APPROVED** [review]

**Comment by swyxio** [comment]
image

**Comment by kevmodrome** [comment]
Netlify Preview Builds help a lot 💩

**Comment by swyxio** [comment]
haha cool

fyi this new version of ssg uses svelte-preprocess under the hood. so we are free to use typescript, or use `<style global>` and anything else they have. still got to work on the docs

**Comment by kevmodrome** [comment]
Very nice! Just using sass is a big bonus in my book. Should probably try using TS as well

**Comment by swyxio** [comment]
feel free to try converting stuff to typescript. i think my ssg docs are very lacking in this regard (basically havent done them yet lol) but i'll get to it eventually haha. all i know is i tried one demo project and it worked so i declared victory

**Pull request merged**
