### PR TITLE
fix(resources): optimize display on narrow viewports

### PR DESCRIPTION
**Pull request by HerrBertling**
in order to have a better mobile view – that was easier and faster than expected 😄 

refs https://github.com/sveltejs/community/issues/116

image

image

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 725b48979717aa13cda84b5b728ea5623f48a157

https://deploy-preview-117--svelte-community.netlify.com

**Review by kevmodrome — APPROVED** [review]
This is great!

**Comment by kevmodrome** [comment]
Could you do this for the Code page as well? Then we can merge this.

Thanks for the work, btw! 👍

**Comment by HerrBertling** [comment]
Yes, I‘ll extract the layout as a slotted component to make it reusable. Noticed the code page only afterwards 😅

**Pull request merged**
