### PR TITLE
Add 'Who is using Sapper' folder

### PR DESCRIPTION
**Pull request by stephane-vanraes**
Adds a folder to gather links and logos for a _Who's using Sapper_ section as described in https://github.com/sveltejs/sapper/issues/1113

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 7fd469df6369d65b9fecd418f252b36c8ff3e67c

https://deploy-preview-178--svelte-community.netlify.app

**Comment by ghost** [comment]
No, this is not right. It duplicates the **Who's using Svelte?** section thus shifting the focus away from Svelte. Also as you can see Sapper's website is way more minimal compared to Svelte's and Svelte is the main technology here. You can't use Sapper without using Svelte.

**Comment by kevmodrome** [comment]
No, this is correct. It was discussed it here: https://github.com/sveltejs/sapper/issues/1113

**Comment by ghost** [comment]
What do you mean this is correct? Just because you discussed it, does not make it right.

**Comment by kevmodrome** [comment]
What I mean is that it's been discussed and has been OK'd on the Sapper repo as something that they would like to add to the website. To me it makes sense that it lives in the same place or close to the "Who's Using Svelte" data.

**Comment by ghost** [comment]
My reasoning is adamant and this will not be merged. I'm becoming a maintainer on https://github.com/sveltejs/sapper as well to help prevent this behavior and its effects on the codebase.

**Comment by pngwn** [comment]
No, you aren't.

**Pull request merged**
