### PR TITLE
Script to update github resources

### PR DESCRIPTION
**Pull request by kevmodrome**
This PR adds a rudimentary script to fetch number of stars as well as last_updated attribute on all the resources that contain "github.com" in it's URL. 

The url for these github resources should be in the following format to work: "https://github.com/organization/repo"

Adds these environment variables:
GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET

### CODE REVIEW

**Comment by kevmodrome** [comment]
I'm going to go ahead and add https://github.com/sveltejs/svelte-virtual-list to improve performance. I'll also do a card style design and add stars + last_updated information :)

**Comment by swyxio** [comment]
very nice work!

maybe instead of last_updated for every field (not very meaningful) we just dump out a "githubLastRunUpdate.json" file with that timestamp? in case we ever need to read it

**Comment by kevmodrome** [comment]
Yeah, that would be fine, I was just thinking it would be nice to see if some package was really old. I'm fine with either.

**Comment by swyxio** [comment]
ohhhh i misunderstood.  i thought it was the time stamp that we ran the script 😅 yes this is great!

**Pull request merged**
