### PR TITLE
added ogma logo + ran prettier

### PR DESCRIPTION
**Pull request by cotlod**
We have a complete frontend svelte application with 18k line of code. A good exemple of Svelte's maintainability with some edge cases encountered! :muscle:

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit b06fd762f0037d1a5af3685afbda6f713f497867

https://deploy-preview-388--svelte-community.netlify.app

**Comment by peopledrivemecrazy** [comment]
@dreitzner what was your prettier config? if there isn't one we could add a config.

**Comment by cotlod** [comment]
> @dreitzner what was your prettier config? if there isn't one we could add a config.

```
  "prettier": {
    "trailingComma": "es5",
    "useTabs": false,
    "tabWidth": 2,
    "semi": false,
    "printWidth": 130,
    "singleQuote": true,
    "quoteProps": "preserve"
  }
```

there you go!

**Comment by dreitzner** [comment]
> @dreitzner what was your prettier config? if there isn't one we could add a config.

Didn't use prettier 😉
But I guess it might be a good idea to copy the editor config and maybe eslintrc from sveltejs/svelte.

Just need to be careful with the actual site, as it may have a different configuration.

**Review by dreitzner — APPROVED** [review]
👍

**Comment by cotlod** [comment]
Hey question, when is it published to svelte.dev? As soon as it's merged into master?

**Comment by swyxio** [comment]
when the svelte core team republishes their site

**Pull request merged**
