### PR TITLE
add moselo logo

### PR DESCRIPTION
**Pull request by priambudiLB**
add moselo logo

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit c436ef2c7f9d2d95e20f95c7c1a368dd3d3b0d9a

https://deploy-preview-375--svelte-community.netlify.app

**Review by dreitzner — APPROVED** [review]
Looks fine

**Comment by swyxio** [comment]
now this is blocked by #377

**Review by dreitzner — CHANGES_REQUESTED** [review]
@priambudiLB please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

**Review by dreitzner — APPROVED** [review]

**Pull request merged**
