### PR TITLE
Fixes githubGetAllData

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 68c93d76382dfe1db602562002b477637d907470

https://deploy-preview-223--svelte-community.netlify.app

**Comment by swyxio** [comment]
thanks for PR! what exactly does this address?

**Comment by ghost** [comment]
Your repositories are not being updated.

**Comment by swyxio** [comment]
heh, had no idea!

**Pull request merged**
