### PR TITLE
docs(whos-using): Added Mail.ru to the list

### PR DESCRIPTION
**Pull request by warmrobot**
Hello!
We're using Svelte on several projects, including homepage.
https://mail.ru/

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 6e5758669ba60ee281a6227d7e48857d355e4b8e

https://deploy-preview-164--svelte-community.netlify.com

**Comment by swyxio** [comment]
hi! sorry gimme 1 sec

**Comment by swyxio** [comment]
welcome aboard Mail.ru!

**Comment by opensas** [comment]
this is really great news!

**Comment by opensas** [comment]
I really hope you can blog about the experience, and some benchmarks about the improvements svelte brought, it's not common to have an insight from such web big players

**Pull request merged**
