### PR TITLE
Fixed typos in README and added BlueHive to WhosUsingSvelte

### PR DESCRIPTION
**Pull request by wreiske**
Hey yall!

This PR fixes some typos in the README and adds https://www.bluehive.com to the WhosUsingSvelte. SVG is optimized with svgo. 

image

Thanks for the awesome project!

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit d3304f6f6570868d6e2b4c36c7ed99a4360052df

https://deploy-preview-61--svelte-community.netlify.com

**Comment by kevmodrome** [comment]
Where are you using Svelte?

**Comment by wreiske** [comment]
> Where are you using Svelte?

We use svelte on a new project we will be releasing in the next couple of months that will be available for over 13,000 occupational health providers in the United States. Our team is also currently converting our production [Meteor](http://meteor.com) / [Blaze](http://blazejs.org/) templates over to use Svelte for bluehive.com. Following https://github.com/meteor-svelte/meteor-svelte closely. We were looking at moving our blaze components to react, but have decided to go with Svelte!!

Planning on doing a writeup of our process converting over to svelte from blaze as well. We are also assessing using svelte in our parent company for our SaaS EHR.

**Review by swyxio — APPROVED** [review]
please swing by and update us when your writeup is done! merging for now

**Pull request merged**
