### PR TITLE
Fixes background colors for logos missing them

### PR DESCRIPTION
**Pull request by ghost**
Updates missing logos with their latest versions
Converts existing colors to hex color code

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit c5e734a3204eace62ca3280ee1e8bbb01a274551

https://deploy-preview-175--svelte-community.netlify.app

**Comment by swyxio** [comment]
very kind of you!

**Comment by swyxio** [comment]
invited you as maintainer!

**Comment by ghost** [comment]
Alright, I will accept.

**Pull request merged**
