### PR TITLE
add npm stats to resources

### PR DESCRIPTION
**Pull request by ryanatkn**
This is a ~~**work in progress**~~ script to add npm stats to the resources.

## design

- include which data? currently just gets ~~weekly~~ monthly downloads
- need to display some form of the info in the ui, possibly replacing the current "npm" link text with the download count - see #31 for the equivalent PR for github stats.

## technical

- uses the npm api documented [here](https://github.com/npm/registry/blob/master/docs/download-counts.md), currently getting ~~weekly~~ monthly download counts
- the current code makes requests one at a time
  - there is a bulk api, but it doesn't work with scoped packages
  - could at least add _some_ concurrency if not custom bulk api code (using bulk api for non-scoped packages)
- should combine with github stat script, either as a serially executed npm script or at the js script level
- include npm api request credentials? I didn't find any info after a quick search and it works ok without

### CODE REVIEW

**Review by kevmodrome — COMMENTED** [review]
This looks dope! Do you want it merged? It has some "wip" wording in there :)

**Comment by ryanatkn** [comment]
I think I misused "wip", the code works but I expected some changes based on the notes above. It could be merged but I'd be happy to wait for more feedback and make any changes.

**Review by kevmodrome — APPROVED** [review]
All rght, i'm going to go ahead and approve it, we should work out some way to run all scripts/combine scripts somehow in the future so we can update everything at once, like you say in the details.

**Comment by ryanatkn** [comment]
I changed the code to pull monthly instead of weekly downloads because it seems like a better indicator of actual usage short of gathering more data points. Would be interested in other POVs.

I also improved the error message and ran the update script to get the initial download counts. Will render them in another PR.

**Comment by ryanatkn** [comment]
Do we want to support retaining yml comments in our data update scripts? I don't see any docs for that in `js-yaml` and my PR here clobbers the couple lines of comments that we had.

**Comment by swyxio** [comment]
i think what will eventually happen is we will have a "source" yml that is then run through the npm and github scraping to output a "destination" yml or json that we then consume. this seems to be the easier way to maintain things.

**Pull request merged**
