### PR TITLE
Implements sorting to repositories

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by swyxio** [comment]
Deploy Preview is done!

Built with commit 1bd929bdab894de7e9d2ed34152a6a2add4fe35f

https://deploy-preview-170--svelte-community.netlify.app

**Comment by swyxio** [comment]
can i get more reasoning on why this PR? is sorting that big an issue? cc @kevmodrome

**Comment by ghost** [comment]
It's just neat.

**Comment by ghost** [comment]
It's a bit of a chaos right now and that way people don't have to wonder where to place their repository since all of them will get sorted anyway.

**Comment by ghost** [comment]
It "evens out the battlefield" from the perspective of someone submitting their code. Eliminates bias towards those placed on top.

**Comment by kevmodrome** [comment]
The reasoning works for me. Guess it also stops people from hijacking the top spot (not that I think that was a problem, though?).

**Comment by ghost** [comment]
@kevmodrome No, I think you've misunderstood. I don't mind someone hijacking the top spot as it's not mine to protect or go after. This PR removes the need for competition. I do however think that the repositories from the official @sveltejs organization should be separated or moved to the top by default in order to have them stand out more. I can submit a proposal if you'd like?

**Comment by ryanatkn** [comment]
I like this more than I rationally should, thank you. 💯 I don't have an opinion about putting official stuff first but it seems easy to do if you like it, doesn't cost anything right?

**Pull request merged**
