### PR TITLE
Devzone tech logo added

### PR DESCRIPTION
**Pull request by antares-code**

### CODE REVIEW

**Comment by swyxio** [comment]
:heavy_check_mark: Deploy Preview is done!


:hammer: Explore the source changes: 2d8bd4bf06407246b76bbb3db7a49931e87af290

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/svelte-community/deploys/60041405edbeed00076233d0](https://app.netlify.com/sites/svelte-community/deploys/60041405edbeed00076233d0?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-374--svelte-community.netlify.app](https://deploy-preview-374--svelte-community.netlify.app?utm_source=github&utm_campaign=bot_dp)

**Review by dreitzner — APPROVED** [review]
seems to look fine

**Comment by swyxio** [comment]
now this is blocked by #377

**Review by dreitzner — CHANGES_REQUESTED** [review]
@antares-code please pull in the latest changes from master and add your info to https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

**Comment by benmccann** [comment]
Thanks. However, we've decided just to feature the most prominent companies using Svelte on the homepage and are no longer featuring sites submitted by the community

**Pull request closed without merging**
